/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Admin
 */

public class frmHeThongNV extends javax.swing.JFrame {

    /**
     * Creates new form frmHeThong
     */
    public frmHeThongNV() {
        initComponents();
        setNULL();
    }
    public void setNULL(){
        jNhanVien.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jNguoiDung = new javax.swing.JMenu();
        jDoiMatKhau = new javax.swing.JMenuItem();
        jThoat = new javax.swing.JMenuItem();
        jDangXuat = new javax.swing.JMenuItem();
        jSanPham = new javax.swing.JMenu();
        jQLSanPham = new javax.swing.JMenuItem();
        jQLNhaCC = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jNhanVien = new javax.swing.JMenuItem();
        jKhachHang = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jHoaDon = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jBaoCaoThongKe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N

        jNguoiDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/1165725.png"))); // NOI18N
        jNguoiDung.setText("Người Dùng");

        jDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/2609282.png"))); // NOI18N
        jDoiMatKhau.setText("Đổi Mật Khẩu");
        jDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDoiMatKhauActionPerformed(evt);
            }
        });
        jNguoiDung.add(jDoiMatKhau);

        jThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/10309351.png"))); // NOI18N
        jThoat.setText("Thoát");
        jThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jThoatActionPerformed(evt);
            }
        });
        jNguoiDung.add(jThoat);

        jDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/4043198.png"))); // NOI18N
        jDangXuat.setText("Đăng Xuất");
        jDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDangXuatActionPerformed(evt);
            }
        });
        jNguoiDung.add(jDangXuat);

        jMenuBar1.add(jNguoiDung);

        jSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/2232688.png"))); // NOI18N
        jSanPham.setText("Sản Phẩm");

        jQLSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/1048927.png"))); // NOI18N
        jQLSanPham.setText("Quản Lý Sản Phẩm");
        jQLSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQLSanPhamActionPerformed(evt);
            }
        });
        jSanPham.add(jQLSanPham);

        jQLNhaCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/10761988.png"))); // NOI18N
        jQLNhaCC.setText("Quản Lý Nhà Cung Cấp");
        jQLNhaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQLNhaCCActionPerformed(evt);
            }
        });
        jSanPham.add(jQLNhaCC);

        jMenuBar1.add(jSanPham);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/3281869.png"))); // NOI18N
        jMenu1.setText("Nhân Viên");

        jNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/staff (1).png"))); // NOI18N
        jNhanVien.setText("Quản lý Nhân Viên");
        jNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNhanVienActionPerformed(evt);
            }
        });
        jMenu1.add(jNhanVien);

        jMenuBar1.add(jMenu1);

        jKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/1605350.png"))); // NOI18N
        jKhachHang.setText("Khách Hàng");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/4149883.png"))); // NOI18N
        jMenuItem1.setText("Quản lý Khách Hàng");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jKhachHang.add(jMenuItem1);

        jMenuBar1.add(jKhachHang);

        jHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/6953015.png"))); // NOI18N
        jHoaDon.setText("Hoá Đơn");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/1037332.png"))); // NOI18N
        jMenuItem3.setText("Quản lý hoá đơn");
        jHoaDon.add(jMenuItem3);

        jMenuBar1.add(jHoaDon);

        jBaoCaoThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/548133.png"))); // NOI18N
        jBaoCaoThongKe.setText("Báo Cáo- Thống Kê");
        jMenuBar1.add(jBaoCaoThongKe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoiMatKhauActionPerformed
        // TODO add your handling code here:
        frmDoiMatKhau frm = new frmDoiMatKhau();
        frm.setVisible(true);
    }//GEN-LAST:event_jDoiMatKhauActionPerformed

    private void jQLSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQLSanPhamActionPerformed
        // TODO add your handling code here:
        frmSanPham frm = new frmSanPham();
        frm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jQLSanPhamActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        frmKhachHang frm = new frmKhachHang();
        frm.setVisible(true); 
        this.hide();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jThoatActionPerformed
        jThoat.addActionListener(e -> {
            System.exit(0);
        });
    }//GEN-LAST:event_jThoatActionPerformed

    private void jQLNhaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQLNhaCCActionPerformed
        // TODO add your handling code here:
        frmNhaCC frm = new frmNhaCC();
        frm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jQLNhaCCActionPerformed

    private void jDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDangXuatActionPerformed
        // TODO add your handling code here:
        frmLogin frm = new frmLogin();
        frm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jDangXuatActionPerformed

    private void jNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNhanVienActionPerformed
        // TODO add your handling code here:
        frmNhanVien frm = new frmNhanVien();
        frm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jNhanVienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHeThongNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHeThongNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHeThongNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHeThongNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHeThongNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jBaoCaoThongKe;
    private javax.swing.JMenuItem jDangXuat;
    private javax.swing.JMenuItem jDoiMatKhau;
    private javax.swing.JMenu jHoaDon;
    private javax.swing.JMenu jKhachHang;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu jNguoiDung;
    private javax.swing.JMenuItem jNhanVien;
    private javax.swing.JMenuItem jQLNhaCC;
    private javax.swing.JMenuItem jQLSanPham;
    private javax.swing.JMenu jSanPham;
    private javax.swing.JMenuItem jThoat;
    // End of variables declaration//GEN-END:variables
}
